### ISSUE TITLE
Limit filesize of log

### ISSUE THREAD

**Issue by JJPPeters** [JJPPeters/clTEM#108]
Currently the log filesize can easily be something massive (tens of GB), which is obviously bad.

**Comment by anashraf002** [comment]
Where is the log file stored? I cannot find any .log file in the clTEM directory in Program Files.

**Comment by JJPPeters** [comment]
The log is in the `%localappdata%` folder (or just `C:\users\<username>\AppData\Local`), then in `\PetersSoft\clTEM/`

It is not recommended that you use the log unless you are having issues. If you are then create a new issue related to that issue.
