### ISSUE TITLE
Request for 2 enhancements (Scripting and Inclusion of TEM incoherence parameters in .json file)

### ISSUE THREAD

**Issue by anashraf002** [JJPPeters/clTEM#118]
1) Include a way to automate simulations through a scripting language and save the data. Right now the only way to create a workable script to simulate and save lots of images is using a screen scraper.

(Possibly a bug)
2) TEM incoherence parameters are not present in the .json file when you try to import a config file. Add the ability to specify TEM imaging incoherence delta and alpha.

**Comment by JJPPeters** [comment]
There is the command line option for the purpose of scripting (i.e. using a batch file or something like python). I would recommend python as it provides functionality to generate/modify the .json configuration files easily. I might at some point include an example script for this.

The second issue is a bug which I have fixed in the main branch. I will package a release shortly.

**Comment by anashraf002** [comment]
> There is the command line option for the purpose of scripting (i.e. using a batch file or something like python). I would recommend python as it provides functionality to generate/modify the .json configuration files easily. I might at some point include an example script for this.

I have already generated 1000 .json files with a python script for a structure I am interested in simulating, however the only way I can load the .json files is using a screen scraper and uploading the .json file one by one. I am interested in the CLI that you talked about, I went through the program file and the only other .exe I found was clTEM_cmd.exe which is not a CLI. Would you please let me know if there is a way to simulate the 1000 pre-prepared .json files for a given structure without using a screen scraper. Thanks.

**Comment by anashraf002** [comment]
> I have already generated 1000 .json files with a python script for a structure I am interested in simulating, however the only way I can load the .json files is using a screen scraper and uploading the .json file one by one. I am interested in the CLI that you talked about, I went through the program file and the only other .exe I found was clTEM_cmd.exe which is not a CLI. Would you please let me know if there is a way to simulate the 1000 pre-prepared .json files for a given structure without using a screen scraper. Thanks.

Nevermind I figured out by reading the src/console/main.cpp there already exists a CLI. I should have been more thorough in my search before posting the question.

**Comment by JJPPeters** [comment]
src/console/main.cpp is the code for clTEM_cmd.exe which is the CLI
