### ISSUE TITLE
Problem regarding the CTEM simulation

### ISSUE THREAD

**Issue by arenal** [JJPPeters/clTEM#121]
There is a problem when doing CTEM simulation. The program reports errors when click the SIM button after setting up the sample structure and the microscope parameters. It asked me to check the log file, but I could not find it.

![image](https://user-images.githubusercontent.com/16731822/104278919-5c22e700-54e4-11eb-98cf-530767cf6165.png)

**Comment by anashraf002** [comment]
Issue has already been answered. 

https://github.com/JJPPeters/clTEM/issues/108
