### ISSUE TITLE
BUG in EW_amplitude.tif, EW_phase.tif, and Diff.tif simulation through command line clTEM_cmd.exe. Error not reproduceable using GUI

### ISSUE THREAD

**Issue by anashraf002** [JJPPeters/clTEM#123]
Whenever I simulate images using the command line invoking the following command for instance: 

> /home/yuki/Documents/Photonics/clTEM/clTEM_source/clTEM_cmd.exe --debug /run/media/yuki/Storage/Documents/Photonics/clTEM/Input Structures/50x50x1_V_B_and_C_N_5_each.xyz -o /home/yuki/Documents/Photonics/clTEM/outputFiles/50x50x1_V_B_and_C_N_5_each/0 -d all -c /home/yuki/Documents/Photonics/clTEM/Input Json Files/0/config.json

with the respective output

> Debug flag is set
>
>Getting OpenCL devices:
>Using all available OpenCL devices
>Platform: 0, device: 0
>        NVIDIA CUDA - NVIDIA GeForce GTX 1060 3GB
>
>Config file: /home/yuki/Documents/Photonics/clTEM/Input Json Files/0/config.json
>Structure file: /run/media/yuki/Storage/Documents/Photonics/clTEM/Input Structures/50x50x1_V_B_and_C_N_5_each.xyz
>Output directory: /home/yuki/Documents/Photonics/clTEM/outputFiles/50x50x1_V_B_and_C_N_5_each/0
>Slice progress: 0%, total progress: 100%         

I get wrong outputs for EW_amplitude.tif and EW_phase.tif since they are cut off horizontally from the middle to the bottom. Diff.tif also is wrong (as in different from the expected output produced when simulating through the GUI) as it only contains a single white pixel in the middle instead of the expected output. The truncated images for the EW only appear when simulating through the command line and do not appear when simulating through the GUI. Attached is the log.log file where I don't see any errors output. 

[log.log](https://github.com/JJPPeters/clTEM/files/6766525/log.log)

Please advise a fix. I need to use the command line since I will be simulating 1000s of images and cannot do it with the GUI.

**Comment by anashraf002** [comment]
![exit waves truncated](https://user-images.githubusercontent.com/51280272/124526399-ab314100-ddd0-11eb-9636-02d7839848e2.png)


Here is an image of the truncated exit waves simulated through the command line.

**Comment by JJPPeters** [comment]
I have identified this issue and fixed it in commit [this commit](https://github.com/JJPPeters/clTEM/commit/1025601c4be19fc06cda70dae2f94c0376cce4e1)

I will make a release soon.

**Comment by JJPPeters** [comment]
See the [latest release](https://github.com/JJPPeters/clTEM/releases/tag/v0.3.4)
