### ISSUE TITLE
Cannot open clTEM

### ISSUE THREAD

**Issue by NJiang1123** [JJPPeters/clTEM#125]
I installed the latest version of clTEM on Mac under Windows (Parallel) interface. The installation went smoothly, but when the program was launched, it display an error message that it could not find the open.dll file and I am forced to quit.

**Comment by JJPPeters** [comment]
If by "open.dll" you mean "opencl.dll", then that means that opencl is not found and needs to be installed.

Unfortunately this is a problem for Parallels (or how you have configured it) that I cannot support.
