### ISSUE TITLE
TEM functionality not working

### ISSUE THREAD

**Issue by enriqueam4** [JJPPeters/clTEM#128]
Hi there,

I've recently tried running TEM simulations on a version of clTEM on Windows 11, and on a clean install of clTEM on Windows 10. I was previously able to use the TEM functionality on an earlier version of windows 10. It should be noted that I can still simulate in STEM and CBED modes, but I need the TEM functionality for research.  The logfile error references the following:

"""
[gui] 2023-06-21 11:42:19,262 (thread:1) ERROR - MainWindow::on_actionImport_default_triggered: Problem importing json settings: Could not open .json file for reading: C:/Users/emejia/AppData/Local/PetersSoft/clTEM/microscopes/default.json
[sim] 2023-06-21 11:42:50,467 (thread:p0:d0) ERROR - SimulationWorker<GPU_Type>::Run: Error performing simulation: Invalid program executable: ccd_ntf_f
Build log:
<kernel>:49:15: error: read-only variable is not assignable  
                input[id].x = real * finalntf;
                ~~~~~~~~~~~ ^
<kernel>:50:15: error: read-only variable is not assignable
                input[id].y = imag * finalntf;
                ~~~~~~~~~~~ ^
"""

Let me know if you have any ideas!

**Comment by JJPPeters** [comment]
I think this issue has been already fixed, though not in the downloadable versions.

In the install directory there is a kernels folder, you can replace all the files inside with the files in the [kernel ](https://github.com/JJPPeters/clTEM/tree/master/kernels) folder from this repository.

**Comment by enriqueam4** [comment]
Appreciate it! Works perfectly now.
